from __future__ import annotations
from pathlib import Path
import copy

PACKAGE_INPUTS = {
    'systemd': ['.file-list-main', '.file-list-pam'],
    'systemd-libs': ['.file-list-libs'],
    'systemd-shared': ['.file-list-shared'],
    'systemd-rpm-macros': ['.file-list-rpm-macros'],
    'systemd-sysusers': ['.file-list-sysusers'],
    'systemd-devel': ['.file-list-devel'],
    'systemd-udev': ['.file-list-udev'],
    'systemd-ukify': ['.file-list-ukify'],
    'systemd-boot-unsigned': ['.file-list-boot'],
    'systemd-machine': ['.file-list-container'],
    'systemd-networkd': ['.file-list-networkd'],
    'systemd-networkd-defaults': ['.file-list-networkd-defaults'],
    'systemd-oomd-defaults': ['.file-list-oomd-defaults'],
    'systemd-journal-remote': ['.file-list-remote'],
    'systemd-resolved': ['.file-list-resolve'],
    'systemd-tests': ['.file-list-tests'],
}

PACKAGE_OUTPUTS = {
    'systemd': '.file-list-main',
    'systemd-libs': '.file-list-libs',
    'systemd-shared': '.file-list-shared',
    'systemd-rpm-macros': '.file-list-rpm-macros',
    'systemd-sysusers': '.file-list-sysusers',
    'systemd-devel': '.file-list-devel',
    'systemd-udev': '.file-list-udev',
    'systemd-ukify': '.file-list-ukify',
    'systemd-boot-unsigned': '.file-list-boot',
    'systemd-factory': '.file-list-factory',
    'systemd-debug': '.file-list-debug',
    'systemd-pcr': '.file-list-pcr',
    'systemd-home': '.file-list-home',
    'systemd-portable': '.file-list-portable',
    'systemd-ssh': '.file-list-ssh',
    'systemd-containerized': '.file-list-containerized',
    'systemd-atomic': '.file-list-atomic',
    'systemd-machine': '.file-list-container',
    'systemd-import': '.file-list-import',
    'systemd-rootless': '.file-list-rootless',
    'systemd-nspawn': '.file-list-nspawn',
    'systemd-vmspawn': '.file-list-vmspawn',
    'systemd-storagetm': '.file-list-storagetm',
    'systemd-journal-remote': '.file-list-remote',
    'systemd-networkd': '.file-list-networkd',
    'systemd-networkd-defaults': '.file-list-networkd-defaults',
    'systemd-oomd-defaults': '.file-list-oomd-defaults',
    'systemd-resolved': '.file-list-resolve',
    'systemd-tests': '.file-list-tests',
    'systemd-zsh-completion': '.file-list-zsh-completion',
    'systemd-firstboot': '.file-list-firstboot',
    'systemd-userdb': '.file-list-userdb',
    'systemd-credentials': '.file-list-credentials',
    'systemd-capsule': '.file-list-capsule',
    'systemd-mute-console': '.file-list-mute-console',
    'systemd-cryptsetup': '.file-list-cryptsetup',
    'systemd-repart': '.file-list-repart',
    'systemd-tpm2': '.file-list-tpm2',
    'systemd-udev-kernelless': '.file-list-udev-kernelless',
}

DIRECT_MOVES = {
    ('systemd', 'systemd-atomic'): [
        '/usr/bin/systemd-confext',
        '/usr/bin/systemd-sysext',
        '/usr/bin/updatectl',
        '/usr/lib/systemd/system/sockets.target.wants/systemd-sysext.socket',
        '/usr/lib/systemd/system/systemd-confext-initrd.service',
        '/usr/lib/systemd/system/systemd-confext.service',
        '/usr/lib/systemd/system/systemd-sysext-initrd.service',
        '/usr/lib/systemd/system/systemd-sysext.service',
        '/usr/lib/systemd/system/systemd-sysext.socket',
        '/usr/lib/systemd/system/systemd-sysext@.service',
        '/usr/share/bash-completion/completions/systemd-confext',
        '/usr/share/bash-completion/completions/systemd-sysext',
        '/usr/share/man/man1/updatectl.1*',
        '/usr/share/man/man5/confext.conf.5*',
        '/usr/share/man/man5/confext.conf.d.5*',
        '/usr/share/man/man5/extension-release.5*',
        '/usr/share/man/man5/sysext.conf.5*',
        '/usr/share/man/man5/sysext.conf.d.5*',
        '/usr/share/man/man8/systemd-confext-initrd.service.8*',
        '/usr/share/man/man8/systemd-confext.8*',
        '/usr/share/man/man8/systemd-confext.service.8*',
        '/usr/share/man/man8/systemd-sysext-initrd.service.8*',
        '/usr/share/man/man8/systemd-sysext.8*',
        '/usr/share/man/man8/systemd-sysext.service.8*',
    ],
    ('systemd', 'systemd-boot-unsigned'): [
        '/usr/lib/systemd/system/systemd-boot-clear-sysfail.service',
        '/usr/lib/systemd/systemd-sbsign',
        '/usr/lib/tmpfiles.d/20-systemd-stub.conf',
        '/usr/share/man/man1/systemd-sbsign.1*',
        '/usr/share/man/man7/linuxaa64.efi.stub.7*',
        '/usr/share/man/man7/linuxia32.efi.stub.7*',
        '/usr/share/man/man7/linuxx64.efi.stub.7*',
        '/usr/share/man/man7/sd-stub.7*',
        '/usr/share/man/man7/systemd-stub.7*',
        '/usr/share/man/man8/systemd-boot-clear-sysfail.service.8*',
    ],
    ('systemd', 'systemd-capsule'): [
        '/usr/lib/systemd/system/capsule.slice',
        '/usr/lib/systemd/system/capsule@.service',
        '/usr/lib/systemd/user/capsule@.target',
        '/usr/share/man/man5/capsule@.service.5*',
    ],
    ('systemd', 'systemd-containerized'): [
        '/usr/lib/systemd/network/80-container-vb.link',
        '/usr/lib/systemd/network/80-container-ve.link',
        '/usr/lib/systemd/network/80-container-vz.link',
        '/usr/lib/systemd/network/80-namespace-ns-tun.link',
        '/usr/lib/systemd/network/80-namespace-ns.link',
        '/usr/lib/systemd/system/console-getty.service',
        '/usr/lib/systemd/system/container-getty@.service',
    ],
    ('systemd', 'systemd-credentials'): [
        '%dir /etc/credstore',
        '%dir /etc/credstore.encrypted',
        '/usr/bin/systemd-creds',
        '%dir /usr/lib/credstore',
        '/usr/lib/systemd/system/sockets.target.wants/systemd-creds.socket',
        '/usr/lib/systemd/system/systemd-creds.socket',
        '/usr/lib/systemd/system/systemd-creds@.service',
        '/usr/lib/tmpfiles.d/credstore.conf',
        '/usr/share/bash-completion/completions/systemd-creds',
        '/usr/share/man/man1/systemd-creds.1*',
    ],
    ('systemd', 'systemd-debug'): [
        '/usr/lib/systemd/system-generators/systemd-debug-generator',
        '/usr/lib/systemd/system/breakpoint-pre-basic.service',
        '/usr/lib/systemd/system/breakpoint-pre-mount.service',
        '/usr/lib/systemd/system/breakpoint-pre-switch-root.service',
        '/usr/lib/systemd/system/debug-shell.service',
        '/usr/lib/systemd/system/sys-kernel-debug.mount',
        '/usr/lib/systemd/system/sysinit.target.wants/sys-kernel-debug.mount',
        '/usr/share/man/man8/systemd-debug-generator.8*',
    ],
    ('systemd', 'systemd-devel'): [
        '/usr/share/pkgconfig/systemd.pc',
        '/usr/share/pkgconfig/udev.pc',
    ],
    ('systemd', 'systemd-factory'): [
        '/usr/lib/systemd/system-generators/systemd-factory-reset-generator',
        '/usr/lib/systemd/system/factory-reset-now.target',
        '/usr/lib/systemd/system/factory-reset.target',
        '%dir /usr/lib/systemd/system/factory-reset.target.wants',
        '/usr/lib/systemd/system/factory-reset.target.wants/systemd-factory-reset-request.service',
        '/usr/lib/systemd/system/sockets.target.wants/systemd-factory-reset.socket',
        '/usr/lib/systemd/system/systemd-factory-reset-complete.service',
        '/usr/lib/systemd/system/systemd-factory-reset-reboot.service',
        '/usr/lib/systemd/system/systemd-factory-reset-request.service',
        '/usr/lib/systemd/system/systemd-factory-reset.socket',
        '/usr/lib/systemd/system/systemd-factory-reset@.service',
        '/usr/lib/systemd/systemd-factory-reset',
        '%dir /usr/share/factory',
        '%dir /usr/share/factory/etc',
        '/usr/share/factory/etc/issue',
        '/usr/share/factory/etc/locale.conf',
        '/usr/share/factory/etc/nsswitch.conf',
        '%dir /usr/share/factory/etc/pam.d',
        '/usr/share/factory/etc/pam.d/other',
        '/usr/share/factory/etc/pam.d/system-auth',
        '/usr/share/man/man8/systemd-factory-reset-complete.service.8*',
        '/usr/share/man/man8/systemd-factory-reset-generator.8*',
        '/usr/share/man/man8/systemd-factory-reset-request.service.8*',
        '/usr/share/man/man8/systemd-factory-reset.8*',
        '/usr/share/man/man8/systemd-factory-reset.socket.8*',
        '/usr/share/man/man8/systemd-factory-reset@.service.8*',
    ],
    ('systemd', 'systemd-firstboot'): [
        '/usr/bin/systemd-firstboot',
        '/usr/lib/systemd/system/sysinit.target.wants/systemd-firstboot.service',
        '/usr/lib/systemd/system/systemd-firstboot.service',
        '/usr/share/man/man1/systemd-firstboot.1*',
        '/usr/share/man/man1/systemd-firstboot.service.1*',
    ],
    ('systemd', 'systemd-home'): [
        '/usr/bin/homectl',
        '/usr/bin/systemd-home-fallback-shell',
        '/usr/lib64/security/pam_systemd_home.so',
        '/usr/lib/systemd/systemd-homework',
        '/usr/lib/tmpfiles.d/home.conf',
        '/usr/share/bash-completion/completions/homectl',
        '/usr/share/man/man1/homectl.1*',
        '/usr/share/man/man8/pam_systemd_home.8*',
    ],
    ('systemd', 'systemd-import'): [
        '/usr/lib/systemd/system/imports-pre.target',
        '/usr/lib/systemd/system/imports.target',
        '/usr/lib/systemd/system/sysinit.target.wants/imports.target',
        '/usr/lib/systemd/system/systemd-loop@.service',
        '/usr/share/man/man7/systemd.image-filter.7*',
        '/usr/share/man/man7/systemd.image-policy.7*',
        '/usr/share/man/man8/systemd-loop@.service.8*',
    ],
    ('systemd', 'systemd-networkd'): [
        '/usr/lib/systemd/network/80-6rd-tunnel.link',
        '/usr/lib/systemd/network/80-vm-vt.link',
    ],
    ('systemd', 'systemd-cryptsetup'): [
        '/usr/lib64/security/pam_systemd_loadkey.so',
        '/usr/share/man/man5/veritytab.5*',
        '/usr/share/man/man8/pam_systemd_loadkey.8*',
    ],
    ('systemd', 'systemd-mute-console'): [
        '/usr/bin/systemd-mute-console',
        '/usr/lib/systemd/system/sockets.target.wants/systemd-mute-console.socket',
        '/usr/lib/systemd/system/system-systemd\\x2dmute\\x2dconsole.slice',
        '/usr/lib/systemd/system/systemd-mute-console.socket',
        '/usr/lib/systemd/system/systemd-mute-console@.service',
        '/usr/share/man/man1/systemd-mute-console.1*',
        '/usr/share/man/man1/systemd-mute-console.socket.1*',
        '/usr/share/man/man1/systemd-mute-console@.service.1*',
    ],
    ('systemd', 'systemd-portable'): [
        '%dir /usr/lib/systemd/portable',
        '%dir /usr/lib/systemd/portable/profile',
        '%dir /usr/lib/systemd/portable/profile/default',
        '/usr/lib/systemd/portable/profile/default/service.conf',
        '%dir /usr/lib/systemd/portable/profile/nonetwork',
        '/usr/lib/systemd/portable/profile/nonetwork/service.conf',
        '%dir /usr/lib/systemd/portable/profile/strict',
        '/usr/lib/systemd/portable/profile/strict/service.conf',
        '%dir /usr/lib/systemd/portable/profile/trusted',
        '/usr/lib/systemd/portable/profile/trusted/service.conf',
        '/usr/lib/tmpfiles.d/portables.conf',
    ],
    ('systemd', 'systemd-repart'): [
        '/usr/lib/systemd/system/systemd-validatefs@.service',
        '/usr/lib/systemd/systemd-validatefs',
        '/usr/share/man/man8/systemd-validatefs@.service.8*',
    ],
    ('systemd', 'systemd-resolved'): [
        '/usr/bin/resolvectl',
        '/usr/lib/systemd/resolv.conf',
        '/usr/share/bash-completion/completions/resolvectl',
        '/usr/share/man/man1/resolvectl.1*',
        '/usr/share/man/man5/dnssec-trust-anchors.d.5*',
        '/usr/share/man/man5/systemd.dns-delegate.5*',
        '/usr/share/man/man5/systemd.dnssd.5*',
        '/usr/share/man/man8/nss-resolve.8*',
    ],
    ('systemd', 'systemd-ssh'): [
        '%dir /etc/ssh',
        '%dir /etc/ssh/ssh_config.d',
        '%config(noreplace) /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf',
        '%dir %attr(0700,root,root) /etc/ssh/sshd_config.d',
        '%dir /usr/lib/systemd/ssh_config.d',
        '/usr/lib/systemd/ssh_config.d/20-systemd-ssh-proxy.conf',
        '%dir /usr/lib/systemd/sshd_config.d',
        '/usr/lib/systemd/sshd_config.d/20-systemd-userdb.conf',
        '/usr/lib/systemd/system-generators/systemd-ssh-generator',
        '/usr/lib/systemd/system/ssh-access.target',
        '/usr/lib/systemd/systemd-ssh-issue',
        '/usr/lib/systemd/systemd-ssh-proxy',
        '/usr/lib/tmpfiles.d/20-systemd-ssh-generator.conf',
        '/usr/share/man/man1/systemd-ssh-issue.1*',
        '/usr/share/man/man1/systemd-ssh-proxy.1*',
        '/usr/share/man/man8/systemd-ssh-generator.8*',
    ],
    ('systemd', 'systemd-storagetm'): [
        '/usr/lib/systemd/system/storage-target-mode.target',
        '%dir /usr/lib/systemd/system/storage-target-mode.target.wants',
        '/usr/lib/systemd/system/systemd-storagetm.service',
        '/usr/lib/systemd/systemd-storagetm',
        '/usr/share/man/man8/systemd-storagetm.8*',
        '/usr/share/man/man8/systemd-storagetm.service.8*',
    ],
    ('systemd', 'systemd-tpm2'): [
        '%dir /usr/lib/nvpcr',
        '/usr/lib/nvpcr/hardware.nvpcr',
        '/usr/lib/systemd/system-generators/systemd-tpm2-generator',
        '/usr/lib/systemd/system/sysinit.target.wants/systemd-tpm2-setup-early.service',
        '/usr/lib/systemd/system/sysinit.target.wants/systemd-tpm2-setup.service',
        '/usr/lib/systemd/system/systemd-tpm2-setup-early.service',
        '/usr/lib/systemd/system/systemd-tpm2-setup.service',
        '/usr/lib/systemd/system/tpm2.target',
        '/usr/lib/systemd/systemd-tpm2-setup',
        '/usr/share/man/man8/systemd-tpm2-generator.8*',
        '/usr/share/man/man8/systemd-tpm2-setup-early.service.8*',
        '/usr/share/man/man8/systemd-tpm2-setup.8*',
        '/usr/share/man/man8/systemd-tpm2-setup.service.8*',
    ],
    ('systemd', 'systemd-udev'): [
        '%dir /usr/lib/systemd/ntp-units.d',
        '/usr/lib/systemd/system-generators/systemd-fstab-generator',
        '/usr/lib/systemd/system-generators/systemd-getty-generator',
        '/usr/lib/systemd/system/bluetooth.target',
        '/usr/lib/systemd/system/emergency.service',
        '/usr/lib/systemd/system/emergency.target',
        '/usr/lib/systemd/system/getty-pre.target',
        '/usr/lib/systemd/system/getty.target',
        '/usr/lib/systemd/system/getty@.service',
        '/usr/lib/systemd/system/modprobe@.service',
        '/usr/lib/systemd/system/multi-user.target.wants/getty.target',
        '/usr/lib/systemd/system/printer.target',
        '/usr/lib/systemd/system/rescue.service',
        '/usr/lib/systemd/system/rescue.target',
        '/usr/lib/systemd/system/serial-getty@.service',
        '/usr/lib/systemd/system/sigpwr.target',
        '/usr/lib/systemd/system/smartcard.target',
        '/usr/lib/systemd/system/sys-kernel-config.mount',
        '/usr/lib/systemd/system/sys-kernel-tracing.mount',
        '/usr/lib/systemd/system/sysinit.target.wants/sys-kernel-config.mount',
        '/usr/lib/systemd/system/sysinit.target.wants/sys-kernel-tracing.mount',
        '/usr/lib/systemd/system/systemd-battery-check.service',
        '/usr/lib/systemd/system/systemd-time-wait-sync.service',
        '/usr/lib/systemd/system/systemd-tpm2-clear.service',
        '/usr/lib/systemd/system/time-set.target',
        '/usr/lib/systemd/system/time-sync.target',
        '/usr/lib/systemd/system/usb-gadget.target',
        '/usr/lib/systemd/systemd-battery-check',
        '/usr/lib/systemd/systemd-sysroot-fstab-check',
        '/usr/lib/systemd/systemd-time-wait-sync',
        '/usr/lib/systemd/systemd-tpm2-clear',
        '/usr/lib/systemd/user/bluetooth.target',
        '/usr/lib/systemd/user/printer.target',
        '/usr/lib/systemd/user/smartcard.target',
        '/usr/share/man/man7/kernel-command-line.7*',
        '/usr/share/man/man8/systemd-battery-check.8*',
        '/usr/share/man/man8/systemd-battery-check.service.8*',
        '/usr/share/man/man8/systemd-fstab-generator.8*',
        '/usr/share/man/man8/systemd-getty-generator.8*',
        '/usr/share/man/man8/systemd-time-wait-sync.8*',
        '/usr/share/man/man8/systemd-time-wait-sync.service.8*',
        '/usr/share/man/man8/systemd-tpm2-clear.service.8*',
    ],
    ('systemd', 'systemd-ukify'): [
        '/usr/share/man/man1/ukify.1*',
    ],
    ('systemd', 'systemd-userdb'): [
        '%dir /etc/userdb',
        '/usr/bin/userdbctl',
        '/usr/lib/systemd/system/systemd-userdb-load-credentials.service',
        '/usr/lib/systemd/system/systemd-userdbd.service',
        '/usr/lib/systemd/system/systemd-userdbd.socket',
        '/usr/lib/systemd/systemd-userdbd',
        '/usr/lib/tmpfiles.d/20-systemd-userdb.conf.example',
        '/usr/share/bash-completion/completions/userdbctl',
        '/usr/share/man/man1/userdbctl.1*',
        '/usr/share/man/man8/systemd-userdbd.8*',
        '/usr/share/man/man8/systemd-userdbd.service.8*',
    ],
    ('systemd', 'systemd-zsh-completion'): [
        '/usr/share/zsh/site-functions/_busctl',
        '/usr/share/zsh/site-functions/_hostnamectl',
        '/usr/share/zsh/site-functions/_journalctl',
        '/usr/share/zsh/site-functions/_localectl',
        '/usr/share/zsh/site-functions/_loginctl',
        '/usr/share/zsh/site-functions/_oomctl',
        '/usr/share/zsh/site-functions/_resolvectl',
        '/usr/share/zsh/site-functions/_run0',
        '/usr/share/zsh/site-functions/_sd_bus_address',
        '/usr/share/zsh/site-functions/_sd_hosts_or_user_at_host',
        '/usr/share/zsh/site-functions/_sd_machines',
        '/usr/share/zsh/site-functions/_sd_outputmodes',
        '/usr/share/zsh/site-functions/_sd_unit_files',
        '/usr/share/zsh/site-functions/_systemctl',
        '/usr/share/zsh/site-functions/_systemd',
        '/usr/share/zsh/site-functions/_systemd-analyze',
        '/usr/share/zsh/site-functions/_systemd-delta',
        '/usr/share/zsh/site-functions/_systemd-id128',
        '/usr/share/zsh/site-functions/_systemd-inhibit',
        '/usr/share/zsh/site-functions/_systemd-path',
        '/usr/share/zsh/site-functions/_systemd-run',
        '/usr/share/zsh/site-functions/_systemd-tmpfiles',
        '/usr/share/zsh/site-functions/_timedatectl',
        '/usr/share/zsh/site-functions/_userdbctl',
        '/usr/share/zsh/site-functions/_varlinkctl',
    ],
    ('systemd-libs', 'systemd'): [
        '/usr/lib64/libnss_myhostname.so.2',
        '/usr/lib64/libnss_systemd.so.2',
        '/usr/share/man/man8/libnss_myhostname.so.2.8*',
        '/usr/share/man/man8/libnss_systemd.so.2.8*',
    ],
    ('systemd-libs', 'systemd-resolved'): [
        '/usr/lib64/libnss_resolve.so.2',
        '/usr/share/man/man8/libnss_resolve.so.2.8*',
    ],
    ('systemd-machine', 'systemd-import'): [
        '/usr/bin/importctl',
        '/usr/bin/mount.ddi',
        '/usr/bin/systemd-dissect',
        '/usr/lib/systemd/import-pubring.pgp',
        '/usr/lib/systemd/system-generators/systemd-import-generator',
        '/usr/lib/systemd/system/dbus-org.freedesktop.import1.service',
        '/usr/lib/systemd/system/sockets.target.wants/systemd-importd.socket',
        '/usr/lib/systemd/system/systemd-importd.service',
        '/usr/lib/systemd/system/systemd-importd.socket',
        '/usr/lib/systemd/systemd-export',
        '/usr/lib/systemd/systemd-import',
        '/usr/lib/systemd/systemd-import-fs',
        '/usr/lib/systemd/systemd-importd',
        '/usr/lib/systemd/systemd-pull',
        '/usr/lib/systemd/user/dbus-org.freedesktop.import1.service',
        '/usr/lib/systemd/user/sockets.target.wants/systemd-importd.socket',
        '/usr/lib/systemd/user/systemd-importd.service',
        '/usr/lib/systemd/user/systemd-importd.socket',
        '/usr/share/bash-completion/completions/importctl',
        '/usr/share/bash-completion/completions/systemd-dissect',
        '/usr/share/dbus-1/interfaces/org.freedesktop.import1.Manager.xml',
        '/usr/share/dbus-1/interfaces/org.freedesktop.import1.Transfer.xml',
        '/usr/share/dbus-1/services/org.freedesktop.import1.service',
        '/usr/share/dbus-1/system-services/org.freedesktop.import1.service',
        '/usr/share/dbus-1/system.d/org.freedesktop.import1.conf',
        '/usr/share/man/man1/importctl.1*',
        '/usr/share/man/man1/mount.ddi.1*',
        '/usr/share/man/man1/systemd-dissect.1*',
        '/usr/share/man/man5/org.freedesktop.import1.5*',
        '/usr/share/man/man8/systemd-import-generator.8*',
        '/usr/share/man/man8/systemd-importd.8*',
        '/usr/share/man/man8/systemd-importd.service.8*',
        '/usr/share/polkit-1/actions/org.freedesktop.import1.policy',
    ],
    ('systemd-machine', 'systemd-nspawn'): [
        '/usr/bin/systemd-nspawn',
        '/usr/lib/systemd/system/systemd-nspawn@.service',
        '/usr/lib/systemd/user/systemd-nspawn@.service',
        '/usr/lib/tmpfiles.d/systemd-nspawn.conf',
        '/usr/share/bash-completion/completions/systemd-nspawn',
        '/usr/share/man/man1/systemd-nspawn.1*',
        '/usr/share/man/man5/systemd.nspawn.5*',
    ],
    ('systemd-machine', 'systemd-portable'): [
        '/usr/bin/portablectl',
        '/usr/share/bash-completion/completions/portablectl',
        '/usr/share/man/man1/portablectl.1*',
    ],
    ('systemd-machine', 'systemd-rootless'): [
        '/usr/lib/systemd/system/systemd-mountfsd.service',
        '/usr/lib/systemd/system/systemd-mountfsd.socket',
        '/usr/lib/systemd/system/systemd-nsresourced.service',
        '/usr/lib/systemd/system/systemd-nsresourced.socket',
        '/usr/lib/systemd/systemd-mountfsd',
        '/usr/lib/systemd/systemd-mountwork',
        '/usr/lib/systemd/systemd-nsresourced',
        '/usr/lib/systemd/systemd-nsresourcework',
        '/usr/share/man/man8/systemd-mountfsd.8*',
        '/usr/share/man/man8/systemd-mountfsd.service.8*',
        '/usr/share/man/man8/systemd-nsresourced.8*',
        '/usr/share/man/man8/systemd-nsresourced.service.8*',
    ],
    ('systemd-machine', 'systemd-vmspawn'): [
        '/usr/bin/systemd-vmspawn',
        '/usr/lib/systemd/system/systemd-vmspawn@.service',
        '/usr/lib/systemd/user/systemd-vmspawn@.service',
        '/usr/share/bash-completion/completions/systemd-vmspawn',
        '/usr/share/man/man1/systemd-vmspawn.1*',
    ],
    ('systemd-machine', 'systemd-zsh-completion'): [
        '/usr/share/zsh/site-functions/_machinectl',
        '/usr/share/zsh/site-functions/_systemd-nspawn',
    ],
    ('systemd-networkd', 'systemd-zsh-completion'): [
        '/usr/share/zsh/site-functions/_networkctl',
    ],
    ('systemd-udev', 'systemd-atomic'): [
        '%dir /usr/lib/systemd/repart/definitions/confext.repart.d',
        '/usr/lib/systemd/repart/definitions/confext.repart.d/10-root.conf',
        '/usr/lib/systemd/repart/definitions/confext.repart.d/20-root-verity.conf',
        '/usr/lib/systemd/repart/definitions/confext.repart.d/30-root-verity-sig.conf',
        '%dir /usr/lib/systemd/repart/definitions/sysext.repart.d',
        '/usr/lib/systemd/repart/definitions/sysext.repart.d/10-root.conf',
        '/usr/lib/systemd/repart/definitions/sysext.repart.d/20-root-verity.conf',
        '/usr/lib/systemd/repart/definitions/sysext.repart.d/30-root-verity-sig.conf',
        '/usr/lib/systemd/system/dbus-org.freedesktop.sysupdate1.service',
        '/usr/lib/systemd/system/initrd.target.wants/systemd-confext-initrd.service',
        '/usr/lib/systemd/system/initrd.target.wants/systemd-sysext-initrd.service',
        '/usr/lib/systemd/system/systemd-sysupdate-reboot.service',
        '/usr/lib/systemd/system/systemd-sysupdate-reboot.timer',
        '/usr/lib/systemd/system/systemd-sysupdate.service',
        '/usr/lib/systemd/system/systemd-sysupdate.timer',
        '/usr/lib/systemd/system/systemd-sysupdated.service',
        '/usr/lib/systemd/systemd-sysupdate',
        '/usr/lib/systemd/systemd-sysupdated',
        '/usr/share/dbus-1/interfaces/org.freedesktop.sysupdate1.Job.xml',
        '/usr/share/dbus-1/interfaces/org.freedesktop.sysupdate1.Manager.xml',
        '/usr/share/dbus-1/interfaces/org.freedesktop.sysupdate1.Target.xml',
        '/usr/share/dbus-1/system-services/org.freedesktop.sysupdate1.service',
        '/usr/share/dbus-1/system.d/org.freedesktop.sysupdate1.conf',
        '/usr/share/man/man5/org.freedesktop.sysupdate1.5*',
        '/usr/share/man/man5/sysupdate.d.5*',
        '/usr/share/man/man5/sysupdate.features.5*',
        '/usr/share/man/man8/systemd-sysupdate-reboot.service.8*',
        '/usr/share/man/man8/systemd-sysupdate-reboot.timer.8*',
        '/usr/share/man/man8/systemd-sysupdate.8*',
        '/usr/share/man/man8/systemd-sysupdate.service.8*',
        '/usr/share/man/man8/systemd-sysupdate.timer.8*',
        '/usr/share/man/man8/systemd-sysupdated.8*',
        '/usr/share/man/man8/systemd-sysupdated.service.8*',
        '/usr/share/polkit-1/actions/org.freedesktop.sysupdate1.policy',
    ],
    ('systemd-udev', 'systemd-boot-unsigned'): [
        '/usr/bin/bootctl',
        '%dir /usr/lib/systemd/boot',
        '/usr/lib/systemd/system/sockets.target.wants/systemd-bootctl.socket',
        '/usr/lib/systemd/system/sysinit.target.wants/systemd-boot-random-seed.service',
        '/usr/lib/systemd/system/systemd-boot-random-seed.service',
        '/usr/lib/systemd/system/systemd-boot-update.service',
        '/usr/lib/systemd/system/systemd-bootctl.socket',
        '/usr/lib/systemd/system/systemd-bootctl@.service',
        '/usr/share/bash-completion/completions/bootctl',
        '/usr/share/man/man1/bootctl.1*',
        '/usr/share/man/man8/systemd-boot-random-seed.service.8*',
    ],
    ('systemd-udev', 'systemd-cryptsetup'): [
        '%ghost %config(noreplace) /etc/crypttab',
        '/usr/bin/systemd-cryptenroll',
        '/usr/bin/systemd-cryptsetup',
        '/usr/lib/systemd/system-generators/systemd-cryptsetup-generator',
        '/usr/lib/systemd/system-generators/systemd-integritysetup-generator',
        '/usr/lib/systemd/system-generators/systemd-veritysetup-generator',
        '/usr/lib/systemd/system/cryptsetup-pre.target',
        '/usr/lib/systemd/system/cryptsetup.target',
        '/usr/lib/systemd/system/initrd-root-device.target.wants/remote-cryptsetup.target',
        '/usr/lib/systemd/system/initrd-root-device.target.wants/remote-integritysetup.target',
        '/usr/lib/systemd/system/initrd-root-device.target.wants/remote-veritysetup.target',
        '/usr/lib/systemd/system/integritysetup-pre.target',
        '/usr/lib/systemd/system/integritysetup.target',
        '/usr/lib/systemd/system/remote-cryptsetup.target',
        '/usr/lib/systemd/system/remote-integritysetup.target',
        '/usr/lib/systemd/system/remote-veritysetup.target',
        '/usr/lib/systemd/system/sysinit.target.wants/cryptsetup.target',
        '/usr/lib/systemd/system/sysinit.target.wants/integritysetup.target',
        '/usr/lib/systemd/system/sysinit.target.wants/veritysetup.target',
        '/usr/lib/systemd/system/system-systemd\\x2dcryptsetup.slice',
        '/usr/lib/systemd/system/system-systemd\\x2dveritysetup.slice',
        '/usr/lib/systemd/system/veritysetup-pre.target',
        '/usr/lib/systemd/system/veritysetup.target',
        '/usr/lib/systemd/systemd-cryptsetup',
        '/usr/lib/systemd/systemd-integritysetup',
        '/usr/lib/systemd/systemd-veritysetup',
        '%dir /usr/lib64/cryptsetup',
        '/usr/lib64/cryptsetup/libcryptsetup-token-systemd-fido2.so',
        '/usr/lib64/cryptsetup/libcryptsetup-token-systemd-pkcs11.so',
        '/usr/lib64/cryptsetup/libcryptsetup-token-systemd-tpm2.so',
        '/usr/share/bash-completion/completions/systemd-cryptenroll',
        '/usr/share/man/man1/systemd-cryptenroll.1*',
        '/usr/share/man/man5/crypttab.5*',
        '/usr/share/man/man5/integritytab.5*',
        '/usr/share/man/man8/systemd-cryptsetup-generator.8*',
        '/usr/share/man/man8/systemd-cryptsetup.8*',
        '/usr/share/man/man8/systemd-cryptsetup@.service.8*',
        '/usr/share/man/man8/systemd-integritysetup-generator.8*',
        '/usr/share/man/man8/systemd-integritysetup.8*',
        '/usr/share/man/man8/systemd-integritysetup@.service.8*',
        '/usr/share/man/man8/systemd-veritysetup-generator.8*',
        '/usr/share/man/man8/systemd-veritysetup.8*',
        '/usr/share/man/man8/systemd-veritysetup@.service.8*',
    ],
    ('systemd-udev', 'systemd-debug'): [
        '/usr/lib/systemd/system/breakpoint-pre-udev.service',
    ],
    ('systemd-udev', 'systemd-factory'): [
        '/usr/share/factory/etc/vconsole.conf',
    ],
    ('systemd-udev', 'systemd-home'): [
        '%config(noreplace) %ghost /etc/systemd/homed.conf',
        '/usr/lib/systemd/homed.conf',
        '/usr/lib/systemd/system/systemd-homed-activate.service',
        '/usr/lib/systemd/system/systemd-homed-firstboot.service',
        '/usr/lib/systemd/system/systemd-homed.service',
        '/usr/lib/systemd/systemd-homed',
        '/usr/share/dbus-1/interfaces/org.freedesktop.home1.Home.xml',
        '/usr/share/dbus-1/interfaces/org.freedesktop.home1.Manager.xml',
        '/usr/share/dbus-1/system-services/org.freedesktop.home1.service',
        '/usr/share/dbus-1/system.d/org.freedesktop.home1.conf',
        '/usr/share/man/man1/systemd-homed-firstboot.service.1*',
        '/usr/share/man/man5/homed.conf.5*',
        '/usr/share/man/man5/homed.conf.d.5*',
        '/usr/share/man/man5/org.freedesktop.home1.5*',
        '/usr/share/man/man8/systemd-homed.8*',
        '/usr/share/man/man8/systemd-homed.service.8*',
        '/usr/share/polkit-1/actions/org.freedesktop.home1.policy',
    ],
    ('systemd-udev', 'systemd-import'): [
        '/usr/lib/udev/rules.d/90-image-dissect.rules',
    ],
    ('systemd-udev', 'systemd-pcr'): [
        '%dir /usr/lib/pcrlock.d',
        '/usr/lib/pcrlock.d/350-action-efi-application.pcrlock',
        '%dir /usr/lib/pcrlock.d/400-secureboot-separator.pcrlock.d',
        '/usr/lib/pcrlock.d/400-secureboot-separator.pcrlock.d/300-0x00000000.pcrlock',
        '/usr/lib/pcrlock.d/400-secureboot-separator.pcrlock.d/600-0xffffffff.pcrlock',
        '%dir /usr/lib/pcrlock.d/500-separator.pcrlock.d',
        '/usr/lib/pcrlock.d/500-separator.pcrlock.d/300-0x00000000.pcrlock',
        '/usr/lib/pcrlock.d/500-separator.pcrlock.d/600-0xffffffff.pcrlock',
        '%dir /usr/lib/pcrlock.d/700-action-efi-exit-boot-services.pcrlock.d',
        '/usr/lib/pcrlock.d/700-action-efi-exit-boot-services.pcrlock.d/300-present.pcrlock',
        '/usr/lib/pcrlock.d/700-action-efi-exit-boot-services.pcrlock.d/600-absent.pcrlock',
        '/usr/lib/pcrlock.d/750-enter-initrd.pcrlock',
        '/usr/lib/pcrlock.d/770-nvpcr-separator.pcrlock',
        '/usr/lib/pcrlock.d/800-leave-initrd.pcrlock',
        '/usr/lib/pcrlock.d/850-sysinit.pcrlock',
        '/usr/lib/pcrlock.d/900-ready.pcrlock',
        '/usr/lib/pcrlock.d/950-shutdown.pcrlock',
        '/usr/lib/pcrlock.d/990-final.pcrlock',
        '/usr/lib/systemd/system/factory-reset.target.wants/systemd-pcrphase-factory-reset.service',
        '/usr/lib/systemd/system/initrd.target.wants/systemd-pcrphase-initrd.service',
        '/usr/lib/systemd/system/sockets.target.wants/systemd-pcrextend.socket',
        '/usr/lib/systemd/system/sockets.target.wants/systemd-pcrlock.socket',
        '/usr/lib/systemd/system/storage-target-mode.target.wants/systemd-pcrphase-storage-target-mode.service',
        '/usr/lib/systemd/system/sysinit.target.wants/systemd-pcrmachine.service',
        '/usr/lib/systemd/system/sysinit.target.wants/systemd-pcrnvdone.service',
        '/usr/lib/systemd/system/sysinit.target.wants/systemd-pcrphase-sysinit.service',
        '/usr/lib/systemd/system/sysinit.target.wants/systemd-pcrphase.service',
        '/usr/lib/systemd/system/sysinit.target.wants/systemd-pcrproduct.service',
        '/usr/lib/systemd/system/systemd-pcrextend.socket',
        '/usr/lib/systemd/system/systemd-pcrextend@.service',
        '/usr/lib/systemd/system/systemd-pcrfs-root.service',
        '/usr/lib/systemd/system/systemd-pcrfs@.service',
        '/usr/lib/systemd/system/systemd-pcrlock-file-system.service',
        '/usr/lib/systemd/system/systemd-pcrlock-firmware-code.service',
        '/usr/lib/systemd/system/systemd-pcrlock-firmware-config.service',
        '/usr/lib/systemd/system/systemd-pcrlock-machine-id.service',
        '/usr/lib/systemd/system/systemd-pcrlock-make-policy.service',
        '/usr/lib/systemd/system/systemd-pcrlock-secureboot-authority.service',
        '/usr/lib/systemd/system/systemd-pcrlock-secureboot-policy.service',
        '/usr/lib/systemd/system/systemd-pcrlock.socket',
        '/usr/lib/systemd/system/systemd-pcrlock@.service',
        '/usr/lib/systemd/system/systemd-pcrmachine.service',
        '/usr/lib/systemd/system/systemd-pcrnvdone.service',
        '/usr/lib/systemd/system/systemd-pcrphase-factory-reset.service',
        '/usr/lib/systemd/system/systemd-pcrphase-initrd.service',
        '/usr/lib/systemd/system/systemd-pcrphase-storage-target-mode.service',
        '/usr/lib/systemd/system/systemd-pcrphase-sysinit.service',
        '/usr/lib/systemd/system/systemd-pcrphase.service',
        '/usr/lib/systemd/system/systemd-pcrproduct.service',
        '/usr/lib/systemd/systemd-pcrextend',
        '/usr/lib/systemd/systemd-pcrlock',
        '/usr/share/man/man5/systemd.pcrlock.5*',
        '/usr/share/man/man5/systemd.pcrlock.d.5*',
        '/usr/share/man/man8/systemd-pcrextend.8*',
        '/usr/share/man/man8/systemd-pcrfs-root.service.8*',
        '/usr/share/man/man8/systemd-pcrfs@.service.8*',
        '/usr/share/man/man8/systemd-pcrlock-file-system.service.8*',
        '/usr/share/man/man8/systemd-pcrlock-firmware-code.service.8*',
        '/usr/share/man/man8/systemd-pcrlock-firmware-config.service.8*',
        '/usr/share/man/man8/systemd-pcrlock-machine-id.service.8*',
        '/usr/share/man/man8/systemd-pcrlock-make-policy.service.8*',
        '/usr/share/man/man8/systemd-pcrlock-secureboot-authority.service.8*',
        '/usr/share/man/man8/systemd-pcrlock-secureboot-policy.service.8*',
        '/usr/share/man/man8/systemd-pcrlock.8*',
        '/usr/share/man/man8/systemd-pcrmachine.service.8*',
        '/usr/share/man/man8/systemd-pcrnvdone.service.8*',
        '/usr/share/man/man8/systemd-pcrphase-initrd.service.8*',
        '/usr/share/man/man8/systemd-pcrphase-sysinit.service.8*',
        '/usr/share/man/man8/systemd-pcrphase.service.8*',
        '/usr/share/man/man8/systemd-pcrproduct.service.8*',
    ],
    ('systemd-udev', 'systemd-portable'): [
        '%dir /usr/lib/systemd/repart/definitions/portable.repart.d',
        '/usr/lib/systemd/repart/definitions/portable.repart.d/10-root.conf',
        '/usr/lib/systemd/repart/definitions/portable.repart.d/20-root-verity.conf',
        '/usr/lib/systemd/repart/definitions/portable.repart.d/30-root-verity-sig.conf',
        '/usr/lib/systemd/system/dbus-org.freedesktop.portable1.service',
        '/usr/lib/systemd/system/systemd-portabled.service',
        '/usr/lib/systemd/systemd-portabled',
        '/usr/share/dbus-1/interfaces/org.freedesktop.portable1.Image.xml',
        '/usr/share/dbus-1/interfaces/org.freedesktop.portable1.Manager.xml',
        '/usr/share/dbus-1/system-services/org.freedesktop.portable1.service',
        '/usr/share/dbus-1/system.d/org.freedesktop.portable1.conf',
        '/usr/share/man/man5/org.freedesktop.portable1.5*',
        '/usr/share/man/man8/systemd-portabled.8*',
        '/usr/share/man/man8/systemd-portabled.service.8*',
        '/usr/share/polkit-1/actions/org.freedesktop.portable1.policy',
    ],
    ('systemd-udev', 'systemd-repart'): [
        '/usr/bin/systemd-repart',
        '%dir /usr/lib/systemd/repart',
        '%dir /usr/lib/systemd/repart/definitions',
        '/usr/lib/systemd/system/initrd-root-fs.target.wants/systemd-repart.service',
        '/usr/lib/systemd/system/sockets.target.wants/systemd-repart.socket',
        '/usr/lib/systemd/system/sysinit.target.wants/systemd-repart.service',
        '/usr/lib/systemd/system/systemd-growfs-root.service',
        '/usr/lib/systemd/system/systemd-growfs@.service',
        '/usr/lib/systemd/system/systemd-repart.service',
        '/usr/lib/systemd/system/systemd-repart.socket',
        '/usr/lib/systemd/system/systemd-repart@.service',
        '/usr/lib/systemd/systemd-growfs',
        '/usr/share/man/man5/repart.d.5*',
        '/usr/share/man/man8/systemd-growfs-root.service.8*',
        '/usr/share/man/man8/systemd-growfs.8*',
        '/usr/share/man/man8/systemd-growfs@.service.8*',
        '/usr/share/man/man8/systemd-repart.8*',
        '/usr/share/man/man8/systemd-repart.service.8*',
    ],
    ('systemd-udev', 'systemd-tpm2'): [
        '/usr/lib/nvpcr/cryptsetup.nvpcr',
        '/usr/lib/systemd/systemd-measure',
        '/usr/share/man/man1/systemd-measure.1*',
    ],
    ('systemd-udev', 'systemd-ukify'): [
        '/usr/lib/kernel/install.d/90-uki-copy.install',
        '/usr/lib/kernel/uki.conf',
    ],
    ('systemd-udev', 'systemd-zsh-completion'): [
        '/usr/share/zsh/site-functions/_bootctl',
        '/usr/share/zsh/site-functions/_coredumpctl',
        '/usr/share/zsh/site-functions/_kernel-install',
        '/usr/share/zsh/site-functions/_systemd-hwdb',
        '/usr/share/zsh/site-functions/_udevadm',
    ],
}

DIRECT_COPIES = {
    ('systemd', 'systemd-udev-kernelless'): [
        '%dir /usr/lib/systemd/ntp-units.d',
        '/usr/lib/systemd/system-generators/systemd-fstab-generator',
        '/usr/lib/systemd/system-generators/systemd-getty-generator',
        '/usr/lib/systemd/system/emergency.service',
        '/usr/lib/systemd/system/emergency.target',
        '/usr/lib/systemd/system/getty-pre.target',
        '/usr/lib/systemd/system/getty.target',
        '/usr/lib/systemd/system/getty@.service',
        '/usr/lib/systemd/system/multi-user.target.wants/getty.target',
        '/usr/lib/systemd/system/rescue.service',
        '/usr/lib/systemd/system/rescue.target',
        '/usr/lib/systemd/system/serial-getty@.service',
        '/usr/lib/systemd/system/systemd-time-wait-sync.service',
        '/usr/lib/systemd/system/time-set.target',
        '/usr/lib/systemd/system/time-sync.target',
        '/usr/lib/systemd/systemd-time-wait-sync',
        '/usr/share/man/man8/systemd-fstab-generator.8*',
        '/usr/share/man/man8/systemd-getty-generator.8*',
        '/usr/share/man/man8/systemd-time-wait-sync.8*',
        '/usr/share/man/man8/systemd-time-wait-sync.service.8*',
    ],
    ('systemd-udev', 'systemd-udev-kernelless'): [
        '%config(noreplace) /etc/sysctl.conf',
        '%dir /etc/sysctl.d',
        '%config(noreplace) /etc/sysctl.d/99-sysctl.conf',
        '%config(noreplace) %ghost /etc/systemd/coredump.conf',
        '%config(noreplace) %ghost /etc/systemd/oomd.conf',
        '%config(noreplace) %ghost /etc/systemd/timesyncd.conf',
        '%dir /usr/lib/sysctl.d',
        '/usr/lib/sysctl.d/10-map-count.conf',
        '/usr/lib/sysctl.d/50-coredump.conf',
        '/usr/lib/sysctl.d/50-default.conf',
        '/usr/lib/sysctl.d/50-pid-max.conf',
        '%doc /usr/lib/sysctl.d/README',
        '/usr/bin/coredumpctl',
        '/usr/lib/systemd/coredump.conf',
        '/usr/lib/systemd/ntp-units.d/80-systemd-timesync.list',
        '/usr/lib/systemd/oomd.conf',
        '/usr/lib/systemd/system-generators/systemd-gpt-auto-generator',
        '/usr/lib/systemd/system/sockets.target.wants/systemd-coredump.socket',
        '/usr/lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup-dev-early.service',
        '/usr/lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup-dev.service',
        '/usr/lib/systemd/system/sysinit.target.wants/systemd-random-seed.service',
        '/usr/lib/systemd/system/sysinit.target.wants/systemd-sysctl.service',
        '/usr/lib/systemd/system/systemd-coredump.socket',
        '/usr/lib/systemd/system/systemd-coredump@.service',
        '/usr/lib/systemd/system/systemd-fsck-root.service',
        '/usr/lib/systemd/system/systemd-fsck@.service',
        '/usr/lib/systemd/system/systemd-oomd.service',
        '/usr/lib/systemd/system/systemd-oomd.socket',
        '/usr/lib/systemd/system/systemd-random-seed.service',
        '/usr/lib/systemd/system/systemd-remount-fs.service',
        '/usr/lib/systemd/system/systemd-sysctl.service',
        '/usr/lib/systemd/system/systemd-timesyncd.service',
        '/usr/lib/systemd/system/systemd-tmpfiles-setup-dev-early.service',
        '/usr/lib/systemd/system/systemd-tmpfiles-setup-dev.service',
        '/usr/lib/systemd/systemd-coredump',
        '/usr/lib/systemd/systemd-fsck',
        '/usr/lib/systemd/systemd-oomd',
        '/usr/lib/systemd/systemd-random-seed',
        '/usr/lib/systemd/systemd-remount-fs',
        '/usr/lib/systemd/systemd-sysctl',
        '/usr/lib/systemd/systemd-timesyncd',
        '/usr/lib/systemd/timesyncd.conf',
        '/usr/lib/sysusers.d/systemd-coredump.conf',
        '/usr/lib/sysusers.d/systemd-timesync.conf',
        '/usr/share/bash-completion/completions/coredumpctl',
        '/usr/share/man/man1/coredumpctl.1*',
        '/usr/share/man/man5/coredump.conf.5*',
        '/usr/share/man/man5/coredump.conf.d.5*',
        '/usr/share/man/man5/oomd.conf.5*',
        '/usr/share/man/man5/oomd.conf.d.5*',
        '/usr/share/dbus-1/system-services/org.freedesktop.timesync1.service',
        '/usr/share/dbus-1/system.d/org.freedesktop.timesync1.conf',
        '/usr/share/man/man8/systemd-coredump.8*',
        '/usr/share/man/man8/systemd-coredump.socket.8*',
        '/usr/share/man/man8/systemd-coredump@.service.8*',
        '/usr/share/man/man8/systemd-oomd.8*',
        '/usr/share/man/man8/systemd-oomd.service.8*',
        '/usr/share/man/man5/org.freedesktop.timesync1.5*',
        '/usr/share/man/man5/sysctl.d.5*',
        '/usr/share/man/man5/timesyncd.conf.5*',
        '/usr/share/man/man5/timesyncd.conf.d.5*',
        '/usr/share/man/man8/systemd-fsck-root.service.8*',
        '/usr/share/man/man8/systemd-fsck-usr.service.8*',
        '/usr/share/man/man8/systemd-fsck.8*',
        '/usr/share/man/man8/systemd-fsck@.service.8*',
        '/usr/share/man/man8/systemd-gpt-auto-generator.8*',
        '/usr/share/man/man8/systemd-tmpfiles-setup-dev-early.service.8*',
        '/usr/share/man/man8/systemd-tmpfiles-setup-dev.service.8*',
        '/usr/share/man/man8/systemd-random-seed.8*',
        '/usr/share/man/man8/systemd-random-seed.service.8*',
        '/usr/share/man/man8/systemd-remount-fs.8*',
        '/usr/share/man/man8/systemd-remount-fs.service.8*',
        '/usr/share/man/man8/systemd-sysctl.8*',
        '/usr/share/man/man8/systemd-sysctl.service.8*',
        '/usr/share/man/man8/systemd-timesyncd.8*',
        '/usr/share/man/man8/systemd-timesyncd.service.8*',
        '/usr/share/polkit-1/actions/org.freedesktop.timesync1.policy',
        '%ghost %dir /var/lib/systemd/coredump',
        '%ghost %attr(0600,root,root) /var/lib/systemd/random-seed',
        '%ghost %dir /var/lib/systemd/timesync',
        '%ghost /var/lib/systemd/timesync/clock',
    ],
}

DIRECT_DROPS = {
    'systemd-udev': [
        '/usr/lib/systemd/system/systemd-network-generator.service',
        '/usr/lib/systemd/systemd-network-generator',
        '/usr/share/man/man8/systemd-network-generator.8*',
        '/usr/share/man/man8/systemd-network-generator.service.8*',
    ],
}

def read_lines(filename: str) -> dict[str, str]:
    path = Path(filename)
    items: dict[str, str] = {}
    if not path.exists():
        return items
    for raw in path.read_text(encoding='utf-8').splitlines():
        if not raw:
            continue
        items[raw] = raw
    return items

def dump_first_stage_inputs() -> None:
    seen: set[str] = set()
    for filenames in PACKAGE_INPUTS.values():
        for filename in filenames:
            if filename in seen:
                continue
            seen.add(filename)
            path = Path(filename)
            print(f'===== BEGIN {filename} =====')
            if path.exists():
                print(path.read_text(encoding='utf-8'), end='')
            else:
                print(f'# MISSING: {filename}')
            print(f'===== END {filename} =====')

dump_first_stage_inputs()

package_to_lines: dict[str, dict[str, str]] = {}
for package, files in PACKAGE_INPUTS.items():
    items: dict[str, str] = {}
    for name in files:
        items.update(read_lines(name))
    package_to_lines[package] = items

for package in PACKAGE_OUTPUTS:
    package_to_lines.setdefault(package, read_lines(PACKAGE_OUTPUTS[package]))

original_package_to_lines = copy.deepcopy(package_to_lines)

for (source, dest), items in DIRECT_MOVES.items():
    for item in items:
        raw = original_package_to_lines[source].get(item)
        if raw is None:
            raise KeyError(f'Missing source entry for move: {source} -> {dest}: {item}')
        if item in package_to_lines[dest]:
            raise KeyError(f'Destination entry already exists for move: {source} -> {dest}: {item}')
        removed = package_to_lines[source].pop(item, None)
        if removed is None:
            raise KeyError(f'Source entry already consumed before move: {source} -> {dest}: {item}')
        package_to_lines[dest][item] = raw

for (source, dest), items in DIRECT_COPIES.items():
    for item in items:
        raw = original_package_to_lines[source].get(item)
        if raw is None:
            raise KeyError(f'Missing source entry for copy: {source} -> {dest}: {item}')
        if item in package_to_lines[dest]:
            raise KeyError(f'Destination entry already exists for copy: {source} -> {dest}: {item}')
        package_to_lines[dest][item] = raw

for source, items in DIRECT_DROPS.items():
    for item in items:
        raw = original_package_to_lines[source].get(item)
        if raw is None:
            raise KeyError(f'Missing source entry for drop: {source}: {item}')
        removed = package_to_lines[source].pop(item, None)
        if removed is None:
            raise KeyError(f'Source entry already consumed before drop: {source}: {item}')

for package, filename in PACKAGE_OUTPUTS.items():
    lines = [raw for _, raw in sorted(package_to_lines[package].items())]
    Path(filename).write_text('\n'.join(lines) + ('\n' if lines else ''), encoding='utf-8')
