name: Rebuild and Upload

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Rebuild SRPM and Upload Copr
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace fedora:latest bash -c '
          dnf install -y dnf-plugins-core patch rpm-build copr-cli &&
          dnf download --source $(find SPECS-PATCHES -name "*.patch" -exec basename {} .patch \; | xargs) &&
          rpm -ivh --define "_topdir /workspace" *.src.rpm &&
          for patch in SPECS-PATCHES/*.patch; do
            pushd SPECS;
            patch -p0 < "../$patch" || exit 1;
            popd;
          done &&
          rpmbuild --define "_topdir /workspace" -bs SPECS/*.spec &&
          echo "${{ secrets.COPR_API }}" > copr-api &&
          . /etc/os-release &&
          copr-cli --config copr-api build --nowait --chroot ${ID}-${VERSION_ID}-$(uname -m) rpm-rebuild SRPMS/*.src.rpm
        '
