name: Rebuild and Upload

on:
  push:
    paths:
      - SPECS-PATCHES/**
  workflow_dispatch:
    inputs:
      package:
        description: Perform operation of
        required: true
        type: string

jobs:
  job:
    runs-on: ubuntu-latest
    container: fedora:${{ github.ref_name }}

    steps:
    - name: Install Dependencies
      run: dnf install -y git-core dnf5-plugins rpmdevtools copr-cli

    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    # Workaround
    - name: Set safe directory
      run: git config --global --add safe.directory ${GITHUB_WORKSPACE}

    - name: Get Packages
      run: |
        case "${{ inputs.package }}" in
          "" )
            packages=$(git diff-tree --diff-filter=AM --no-commit-id --name-only -r HEAD -- SPECS-PATCHES | sed -E "s|.*/||; s/\.patch\$//")
            ;;
          "_all" )
            packages=$(find SPECS-PATCHES -name "*.patch" -exec basename {} .patch \;)
            ;;
          * )
            packages=""
            for pkg in ${{ inputs.package }}; do
              if [[ -f "SPECS-PATCHES/${pkg}.patch" ]]; then
                packages+="${pkg} "
              else
                echo "::warning::Patch not found for: ${pkg}"
              fi
            done
            ;;
        esac

        if [[ -z "${packages}" ]]; then
          echo "::warning::No packages to build."
        else
          echo "packages=$(echo "${packages}" | xargs)" >> $GITHUB_ENV
        fi

    - name: Rebuild SRPM
      if: env.packages
      run: |
        dnf download --source ${packages}
        rpm -ivh --define "_topdir ${GITHUB_WORKSPACE}" *.src.rpm
        for pkg in ${packages}; do
          echo "Apply patch for ${pkg}"
          sed -i "s/[[:space:]]\+\$//" SPECS/${pkg}.spec
          git apply --directory SPECS -C 1 -p 1 SPECS-PATCHES/${pkg}.patch
          if [[ $? -ne 0 ]]; then
            echo "::error::Patch applied failed for ${pkg}"
            exit 1
          else
            echo "Patch applied successfully for ${pkg}"
            spectool --define "_topdir ${GITHUB_WORKSPACE}" --get-files --sourcedir --patches SPECS/${pkg}.spec
          fi
        done
        rpmbuild --define "_topdir ${GITHUB_WORKSPACE}" -bs SPECS/*.spec

    - name: Upload Copr
      if: env.packages
      run: |
        echo "${{ secrets.COPR_API }}" > copr-api
        . /etc/os-release
        copr-cli --config copr-api build --nowait --timeout 86400 --chroot ${ID}-${VERSION_ID}-$(uname -m) $(echo ${GITHUB_REPOSITORY} | cut -d "-" -f 2-) SRPMS/*.src.rpm
        echo "::notice::Packages to build: ${packages}"
