name: Rebuild RPM

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Rebuild RPM
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace fedora:latest bash -c "
          dnf install -y dnf-plugins-core rpmdevtools rpmrebuild &&
          dnf download filesystem &&
          rpmrebuild --package --directory /workspace --spec-only SPECS/filesystem.spec *.rpm &&
          ls -l &&
          cat SPECS/*.spec #&&
          #spectool --get-files --all SPECS/*.spec &&
          #rpmbuild --define '_topdir /workspace' -ba SPECS/*.spec
        "

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rpm-package
        path: RPMS/
