name: Rebuild and Upload

on:
  push:
    branches:
      - "f[0-9]+"
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
    - name: Get Version
      run: echo "version=$(echo ${GITHUB_REF#refs/heads/} | grep -o '[0-9]*')" >> $GITHUB_ENV

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Rebuild SRPM and Upload Copr
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace fedora:${{ env.version }} bash -c '
          dnf install -y dnf-plugins-core patch rpm-build copr-cli &&
          dnf download --source $(find SPECS-PATCHES -name "*.patch" -exec basename {} .patch \; | xargs) &&
          rpm -ivh --define "_topdir /workspace" *.src.rpm &&
          for patch in SPECS-PATCHES/*.patch; do
            pushd SPECS > /dev/null;
            patch -p0 < "../$patch" || { echo "Patch $patch Failed!"; exit 1; }
            popd  > /dev/null;
          done &&
          rpmbuild --define "_topdir /workspace" -bs SPECS/*.spec &&
          echo "${{ secrets.COPR_API }}" > copr-api &&
          . /etc/os-release &&
          copr-cli --config copr-api build --nowait --chroot ${ID}-${VERSION_ID}-$(uname -m) rpm-rebuild SRPMS/*.src.rpm
        '
