name: Rebuild RPM

on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Prepare Source
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace fedora:latest bash -c '
          dnf install -y dnf-plugins-core patch &&
          dnf download --source $(find SPECS-PATCHES -name "*.patch" -exec basename {} .patch \; | xargs) &&
          rpm -ivh --define "_topdir /workspace" *.src.rpm &&
          for patch in SPECS-PATCHES/*.patch; do
            pushd SPECS;
            patch -p0 < "../$patch" || exit 1;
            popd;
          done
        '

    - name: Rebuild SRPM
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace fedora:latest bash -c '
          dnf install -y rpm-build &&
          rpmbuild --define "_topdir /workspace" -bs SPECS/*.spec
        '

    - name: Upload SRPM
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace fedora:latest bash -c '
          echo "${{ secrets.COPR_API }}" > copr-api &&
          dnf install -y copr-cli &&
          copr-cli --config copr-api build --nowait --chroot fedora-$(rpm -E %fedora)-x86_64 rpm-rebuild SRPM/*.src.rpm
        '
