name: Rebuild RPM

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Rebuild RPM
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace fedora:latest bash -c "
          dnf install -y dnf-plugins-core rpmrebuild &&
          dnf download filesystem &&
          rpmrebuild --package --directory /workspace --modify 'sed -e "/\/afs/d"' *.rpm
        "

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rpm-package
        path: x86_64/
