name: Check and Trigger

on:
  schedule:
    - cron: '0 0 */5 * *'  # Runs per 5 days at midnight UTC
  workflow_dispatch:

permissions:
  actions: write

jobs:
  job:
    runs-on: ubuntu-latest
    container: fedora:${{ github.ref_name }}

    steps:
    - name: Install Dependencies
      run: dnf install -y git-core

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Generate Version
      run: |
        touch Version
        for pkg in $(find SPECS-PATCHES -name "*.patch" -exec basename {} .patch \; | sort); do
          ver=$(dnf repoquery --qf "%{Version}-%{Release}" ${pkg} --latest-limit=1 --repo=fedora-source --repo=updates-source 2>/dev/null)
          if [ -z "${ver}" ]; then
            echo "::warning::Not found ${pkg}"
          else
            echo "${pkg} ${ver}" >> Version
          fi
        done

    - name: Cache Version
      uses: actions/cache@v4
      id: cache
      with:
        key: cache-version-${{ github.ref_name }}-${{ hashFiles('Version') }}
        restore-keys: cache-version-${{ github.ref_name }}
        path: VERSION

    - name: Compare Version
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        packages=""
        touch VERSION
        while read -r pkg ver; do
          row=$(grep -E "^${pkg} " VERSION || true)
          if [ -n "${row}" ]; then
            if [ $(echo "${row}" | awk "{print \$2}") != "${ver}" ]; then
              echo "::notice::Updating ${pkg} to ${ver}"
              packages+="${pkg} "
            fi
          else
            echo "New package ${pkg} with version ${ver}"
          fi
        done < Version
        mv Version VERSION
        if [ -z "${packages}" ]; then
          echo "::notice::No packages updated"
        else
          echo "::notice::Packages to update: ${packages}"
          echo "packages=${packages}" >> ${GITHUB_ENV}
        fi

    - name: Trigger Build
      if: env.packages
      uses: actions/github-script@v8
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'main.yml',
            ref: context.ref,
            inputs: {
              packages: process.env.packages
            }
          });
