name: Check and Trigger

on:
  schedule:
    - cron: '0 0 */5 * *'  # Runs per 5 days at midnight UTC
  workflow_dispatch:

permissions:
  actions: write

jobs:
  job:
    runs-on: ubuntu-latest
    container: fedora:${{ github.ref_name }}

    steps:
    - name: Install Dependencies
      run: dnf install -y git-core gawk

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Cache Version
      uses: actions/cache@v4
      with:
        path: VERSION
        key: cache-version-${{ github.ref_name }}

    - name: Check Version
      run: |
        packages=""
        for pkg in $(find SPECS-PATCHES -name '*.patch' -exec basename {} .patch \; | sort); do
          ver=$(dnf repoquery --qf "%{Version}-%{Release}" ${pkg} --latest-limit=1 --repo=fedora-source --repo=updates-source 2>/dev/null)
          if [ -z "${ver}" ]; then
            echo "::warning::Not found ${pkg}"
          else
            if grep -E "^${pkg} " VERSION 2>&1 >/dev/null; then
              if [ $(grep -E "^${pkg} " VERSION | awk "{print \$2}") == "${ver}" ]; then
                echo "No changes for ${pkg} (${ver})"
              else
                echo "::notice::Updating ${pkg} to ${ver}"
                packages+="${pkg} "
              fi
            else
              echo "::notice::Adding new package ${pkg} (${ver})"
            fi
            echo "${pkg} ${ver}" >> VERSION.new
          fi
        done
        mv VERSION.new VERSION
        if [ -z "${packages}" ]; then
          echo "::notice::No packages updated"
        else
          echo "::notice::Packages to update: ${packages}"
          echo "packages=${packages}" >> ${GITHUB_ENV}
        fi

    - name: Trigger Build
      if: env.packages
      uses: actions/github-script@v8
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'main.yml',
            ref: context.ref,
            inputs: {
              packages: process.env.packages
            }
          });
